In [1]:
import cv2
import numpy as np

In [8]:
img = cv2.imread('mavic_air.jpg')
cv2.imshow('img', img)
grayImg = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
grayImg = np.float32(grayImg)
# 图片 邻域大小 孔径大小 k系数
harriImg = cv2.cornerHarris(grayImg, 2, 3, 0.04)
# 膨胀
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
harriImgD = cv2.dilate(harriImg, kernel)
# 设置阈值
img[harriImgD > 0.05*harriImgD.max()] = [0,0,255]
cv2.imshow('Harri', harriImgD)
cv2.imshow('Output', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
img = cv2.imread('mavic_air.jpg')
grayImg = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# 图像 最大角点数量 最小特征值 最小距离
cornerPoints = cv2.goodFeaturesToTrack(grayImg, 50,
                                      0.01, 50)
cornerPoints = np.int0(cornerPoints)
for i in cornerPoints:
    x, y = i.ravel()
    cv2.circle(img, (x,y), 3, [0,0,255], -1)
    
cv2.imshow('Shi-Tomasi', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
img = cv2.imread('mavic_air.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

gray32 = np.float32(gray)
dst = cv2.cornerHarris(gray, 2, 3, 0.04)
dst = cv2.dilate(dst, None)
ret, dst = cv2.threshold(dst, 0.01*dst.max(), 255, 0)
dst = np.uint8(dst)
cv2.imshow('dst', dst)

ret, labels, stats, centroids = cv2.connectedComponentsWithStats(dst)
# 确定亚像素角点检测的迭代条件
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 0.001)
corners = cv2.cornerSubPix(gray32, np.float32(centroids), (5, 5), (-1, -1), criteria)

# 使用Shi-Tomasi算法找到角点
cornerPoints = cv2.goodFeaturesToTrack(gray, 50, 0.01, 50)
cornersS = cv2.cornerSubPix(gray, cornerPoints, (5, 5), (-1, -1), criteria)
# 横向堆叠矩心和角点的坐标矩阵
res = np.hstack((centroids, corners))
res = np.int0(res)
print(res)
# 蓝色点表示Harri算法后找到的角点
# 绿色点表示Harri算法后和连通域找到的亚像素角点
# 红色点表示Shi-Tomasi算法后找到的亚像素角点
for i in cornersS:
    x, y = i.ravel()
    cv2.circle(img, (x, y), 4, [0, 0, 255])
for i in range(0, res[:, 3].size):
    cv2.circle(img, (res[i, 0], res[i, 1]), 4, [255, 0, 0])
    cv2.circle(img, (res[i, 2], res[i, 3]), 3, [0, 255, 0])
cv2.imshow('Image', img)


cv2.waitKey()
cv2.destroyAllWindows()

[[359 172 363 170]
 [398  46 399  44]
 [518  47 516  47]
 [528  48 527  46]
 [574  79 574  80]
 [306  84 311  81]
 [434  83 436  80]
 [567  81 567  81]
 [282  88 280  86]
 [452  87 452  87]
 [471  87 472  86]
 [290  89 289  87]
 [432  89 432  89]
 [546  96 544  94]
 [316  98 314  98]
 [183 101 180 101]
 [553 100 553  99]
 [336 102 336 102]
 [436 102 433 101]
 [293 104 293 104]
 [295 111 295 111]
 [554 121 554 121]
 [398 123 398 123]
 [618 124 618 124]
 [555 126 554 127]
 [144 128 144 126]
 [604 128 602 128]
 [131 130 130 129]
 [555 147 554 145]
 [563 149 565 149]
 [148 170 148 170]
 [134 197 134 197]
 [224 188 223 188]
 [120 196 116 200]
 [117 202 116 200]
 [465 202 466 199]
 [229 210 228 206]
 [435 209 434 207]
 [338 211 338 210]
 [313 220 310 219]
 [183 221 181 221]
 [204 221 205 221]
 [120 222 118 225]
 [305 223 303 222]
 [315 232 317 231]
 [477 232 476 230]
 [282 236 282 236]
 [368 240 366 240]
 [437 239 438 239]
 [390 246 391 246]
 [132 268 132 269]
 [464 318 463 319]]
