In [23]:
import numpy as np
a = np.array([[2, 23, 4],
              [2, 32, 4]])
print(a)
print(a.ndim) # 维数
print(a.shape) # 形状
print(a.size) # 元素个数
b = np.ones((2, 3)) # 全是1的矩阵
print(b)
c = np.empty((3, 4)) # 空矩阵，实际上元素接近0
print(c)
d = np.arange(10, 22, 2) # 从10到20，间隔2
print(d)
d = d.reshape(2, 3)
print(d)

[[ 2 23  4]
 [ 2 32  4]]
2
(2, 3)
6
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 12 14 16 18 20]
[[10 12 14]
 [16 18 20]]


In [52]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
print(a, b)
print(a - b)
c = 10**2 # 每个元素平方
print(c)
print(b<3)

[10 20 30 40] [0 1 2 3]
[10 19 28 37]
100
[ True  True  True False]


In [51]:
a = np.array([10, 20, 30, 40])
b = np.arange(4) # 0~3
print(a, b)
c = 10 * np.sin(a)#正弦
print(c)
print(b<3)

[10 20 30 40] [0 1 2 3]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[ True  True  True False]


In [6]:
a = np.array([[1, 1],
              [0, 1]])
b = np.arange(4).reshape(2, 2)
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [8]:
c = a * b # 按位置相乘
c_dot = np.dot(a, b) # 矩阵乘法
c_dot_2 = a.dot(b) # 同上
print(c)
print(c_dot)
print(c_dot_2)

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [14]:
a = np.random.random((2, 4)) # 随机
print(a)
print(np.sum(a), np.min(a), np.max(a)) # 求和，最小，最大
print(np.max(a, axis=1), np.max(a, axis=0)) # 按列/按行求最大/最小

[[0.7823079  0.64430479 0.88445099 0.53965194]
 [0.76002715 0.90000712 0.38251778 0.7867779 ]]
5.680045577942661 0.3825177766959976 0.9000071208081233
[0.88445099 0.90000712] [0.7823079  0.90000712 0.88445099 0.7867779 ]


In [56]:
A = np.arange(14, 2, -1).reshape((3, 4))
print(A)
print(np.argmin(A), np.argmax(A)) # 最小，最大的位置
print(np.mean(A), A.mean(), np.average(A)) # 平均数
print(np.mean(A, axis=0)) # 按列求平均数
print(np.median(A)) # 平均数
print(np.cumsum(A)) # 累加
print(np.diff(A)) # 相邻元素差
print(np.nonzero(A)) # 非零值的行和列
print(np.sort(A)) # 按行排序
print(np.transpose(A)) # 转置
print(A.T) # 还是转置
print((A.T).dot(A))
print(np.clip(A, 5, 9))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
11 0
8.5 8.5 8.5
[10.  9.  8.  7.]
8.5
[ 14  27  39  50  60  69  77  84  90  95  99 102]
[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [75]:
A = np.arange(3, 15).reshape((3, 4))
print(A)
print(A[2]) # 第二行
print(A[2][2], A[2, 2]) # 第二行第二列的元素
print(A[1, :], A[:, 1]) # 第一行/第一列
print(A[0:2, 1:3])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
13 13
[ 7  8  9 10] [ 4  8 12]
[[4 5]
 [8 9]]


In [78]:
for row in A: # 遍历行
    print(row)
for col in A.T: # 遍历列
    print(col)
print(A.flatten()) # A.flatten是每个元素的值
for item in A.flat: # 遍历元素 A.flat是迭代器
    print(item)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [100]:
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])
C = np.vstack((A, B)) # 上下合并
D = np.hstack((A, B)) # 左右合并
print(A.shape, C.shape, D.shape)
print(C, D) 
E = A[np.newaxis, :] # 增加列维度
F = A[:, np.newaxis] # 增加行维度
print(A, A.shape, E, E.shape, F, F.shape)
G = B[:, np.newaxis]
print(np.hstack((F, G))) # 将A和B竖着合并
C = np.concatenate((F, G, G, F), axis=0)
print(C)
C = np.concatenate((F, G, G, F), axis=1)
print(C)


(3,) (2, 3) (6,)
[[1 1 1]
 [2 2 2]] [1 1 1 2 2 2]
[1 1 1] (3,) [[1 1 1]] (1, 3) [[1]
 [1]
 [1]] (3, 1)
[[1 2]
 [1 2]
 [1 2]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [111]:
A = np.arange(12).reshape((3, 4))
print(A)
print(np.split(A, 2, axis=1)) # 纵向分割
print(np.split(A, 3, axis=0)) # 横向分割
print(np.array_split(A, 3, axis=1)) # 不等分割,纵向
print(np.hsplit(A, 2)) # 不等分割，水平（纵向）
print(np.vsplit(A, 3)) # 不等分割，垂直（横向）

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [121]:
a = np.arange(4).reshape(2, 2)
b = a # 浅拷贝
a[0][0] = 11
print(a) # a和b同时改变
print(b)
print(b is a)
c = a.copy() # 不太深的拷贝
a[1][1] = 44
print(a)
print(c)

[[11  1]
 [ 2  3]]
[[11  1]
 [ 2  3]]
True
[[11  1]
 [ 2 44]]
[[11  1]
 [ 2  3]]


In [122]:
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')]) # 结构化数据类型
print(student)
a = np.array([('abc', 21, 50), ('xyz', 18, 75)], dtype = student)
print(a)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [125]:
x = [1, 2, 3]
a = np.asarray(x, dtype = float)
print(a)

[1. 2. 3.]


In [126]:
list = range(5)
it = iter(list) #迭代器

x = np.fromiter(it, dtype=float) # 从迭代器转回来
print(x)

[0. 1. 2. 3. 4.]


In [128]:
a = np.logspace(1, 2, num = 10) # 底数默认为10，产生10个元素
print(a)
a = np.logspace(0, 9, 10, base=2) # 底数改为2，产生10个元素
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


In [129]:
x = np.array([
    [1, 2],
    [3, 4],
    [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]] # 指定行，指定列
print(y)

[1 4 5]


In [131]:
a = np.array([
    [0, 0, 0],
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30]
])
b = np.array([1, 2, 3])
print(a + b) # 广播
bb = np.tile(b, (4, 1)) # 手动在行上重复
print(bb)
print(a + bb) # 结果同广播

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [133]:
# 以下例子说明a和a.T在内存中的存储顺序相同
a = np.arange(6).reshape(2, 3)
for x in np.nditer(a): # 迭代器
    print(x, end=", ")
print('\n')
for x in np.nditer(a.T):
    print(x, end=", ")
print('\n')
for x in np.nditer(a.T.copy(order='C')):
    print(x, end=", ")
print('\n')

0, 1, 2, 3, 4, 5, 

0, 1, 2, 3, 4, 5, 

0, 3, 1, 4, 2, 5, 



In [144]:
a = np.array([0, 3, 4, 2, 1])
print(np.partition(a, 2)) # 小于3放前面，其余放后面

[0 1 2 4 3]


In [143]:
print(np.partition(a, (1, 3))) # 小于1放前面,大于3后面，其余中间

[0 1 2 3 4]


In [147]:
import numpy.matlib
print(np.matlib.eye(n = 3, M = 4, k = 0, dtype=float)) # 对角线矩阵
print(np.matlib.identity(5, dtype=float)) # 单位矩阵

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [148]:
i = np.matrix('1,2;3,4') # 产生一个矩阵
print(i)
j = np.asarray(i) # 矩阵转数组
print(j)
k = np.asmatrix(j) # 数组转矩阵
print(k)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [153]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
bb = [1, 2]
print(np.matmul(a, b)) # 矩阵乘法
print(np.matmul(a, bb))
c = np.arange(8).reshape(2, 2, 2)
d = np.arange(4).reshape(2, 2)
print(np.matmul(c, d))
print(np.linalg.det(a)) # 求行列式

[[4 1]
 [2 2]]
[1 2]
[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]]
1.0


In [161]:
a = np.array([[1, 1, 1], [0, 2, 5], [2, 5, -1]])
ainv = np.linalg.inv(a) # a的逆
b = np.array([6, -4, 27])[:, np.newaxis]
bb = np.array([6, -4, 27])[np.newaxis, :]
print(b)
print(bb.T)
x = np.linalg.solve(a, b) # 解线性方程
print(x)
x = np.linalg.solve(a, bb.T) # 解线性方程
print(x)

[[ 6]
 [-4]
 [27]]
[[ 6]
 [-4]
 [27]]
[[ 5.]
 [ 3.]
 [-2.]]
[[ 5.]
 [ 3.]
 [-2.]]
